### ISSUE TITLE
Improve horrible Quadrant management

### ISSUE THREAD

**Issue by ghost** [MathieuLebeuf/SudokuSolver#2]
All these if-else could be replaced by a simple modulo usage

https://github.com/MathieuLebeuf/SudokuSolver/blob/64facbd3d69b1866bfd5b73d349f2a33e71abfc8/SudokuSolverLibrary/Sudoku_Board.cs#L139

**Comment by MathieuLebeuf** [comment]
Horrible is no more.

**Comment by MathieuLebeuf** [comment]
Horrible is no more.

            int modRow = row - (row %3);
            int modCol = col - (col %3);

            // Verify bloc.
            for (int k = 0; k < 3; k++)
            {
                for (int l = 0; l < 3; l++)
                {
                    if (board[k + modRow, l + modCol] == n)
                    {
                        return false;
                    }
                }
            }
